on: issue_comment
name: Review Requester
jobs:
  examineComment:
    name: what's in the comment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: examine the comment
      uses: ./review-requester
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
